# Generated by Django 3.1.4 on 2022-02-08 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_auto_20190731_1653'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='blorejobs',
            new_name='babglorejobs',
        ),
    ]
